name: dwayne
favicon: null
layout_spectrum: 0.31759286927990615
typography_spectrum: 0.2589710436295718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#74b5f5'
    - '#365011'
    - '#65882a'
    - '#142b00'
    - '#7fad31'
  brandStrength: 0.125
  lightness: 0.4826264977455139
  saturation: 0.6650433712638915
  rhythmicContrast: 0.7870713223237544
purpose: []
