name: dwayne
favicon: null
layout_spectrum: 0.31759286927990615
typography_spectrum: 0.2589710436295718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.08045017789117992
  lightness: 0.4826264977455139
  saturation: 0.6650433712638915
  rhythmicContrast: 0.7870713223237544
purpose: []
